<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Bug kiosk</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>

        <h1>Home</h1>

<?php
   
   if (isset($user))
   {
       echo "<h4>Welcome $user->firstname!</h4>";
   }
   else
   {
       echo "Something went wrong :(";
       echo "<br>";
       echo "Invalid session, please log in using valid credentials!";
   }
   
?>
<div class="row">
    <a  href="/logout" class="waves-effect waves-light btn-large"><i class="material-icons right">exit_to_app</i>Logout</a>
</div>
</body>
</html>