<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Bug register</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <style>

        </style>
    </head>
    <body>
        <div class="register">
        <h1>Register</h1>

        <form class="col s12" method="POST" action="/register">

        <div class="form">
            <div class="row">
                <div class="row">
                    <div class="input-field col s3" style="margin-left:36%">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="username" required="required" name="username" type="text"  class="validate">
                    <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s3" style="margin-left:36%">
                    <i class="material-icons prefix">lock</i>
                    <input id="password" required="required" name="password" type="password" class="validate">
                    <label for="password">Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s3" style="margin-left:36%">
                    <i class="material-icons prefix">lock</i>
                    <input id="confirmpassword" required="required" name="confirmpassword" type="password" class="validate">
                    <label for="confirmpassword">Confirm Password</label>
                    </div>
                </div>
                </div>
                <div class="row">
                    <a  href="/" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
                    <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Register<i class="material-icons right">send</i></button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        </div>
    </body>
</html>
