<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Bug register</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <link rel="stylesheet" href="css/style.css">
        <style>
        </style>
    </head>
    <body>
        <div class="register">
        <h1>Register</h1>

        <div class="form">
            <div class="row">
                <form class="col s6 offset-s3" method="POST" action="/register">
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="m_input" required="required" name="first_name" type="text" class="validate">
                    <label for="m_input">First Name</label>
                    </div>
                    <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="m_input" required="required" name="last_name" type="text"  class="validate">
                    <label for="m_input">Last Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                    <i class="material-icons prefix">lock</i>
                    <input id="m_input" required="required" name="password" type="password" class="validate">
                    <label for="m_input">Password</label>
                    </div>
                    <div class="input-field col s6">
                    <i class="material-icons prefix">lock</i>
                    <input id="m_input" required="required" name="confirmpassword" type="password" class="validate">
                    <label for="m_input">Confirm Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s8">
                    <i class="material-icons prefix">email</i>
                    <input id="m_input" name="email" required="required" type="email" class="validate">
                    <label for="m_input">E-mail</label>
                    <span class="helper-text" data-error="Invalid e-mail!" data-success="Valid e-mail."></span>
                    </div>
                    <div class="input-field col s4">
                    <i class="material-icons prefix">account_circle</i>
                    <input id="m_input" type="text" class="validate" name="short_name" required="required">
                    <label for="m_input">4-letter username</label>
                    </div>
                </div>
                <div class="row">
                    <a  href="/" class="waves-effect waves-light btn-large"><i class="material-icons right">arrow_back</i>Back</a>
                    <button class="btn waves-effect waves-light btn-large" type="submit" name="action">Register<i class="material-icons right">send</i></button>
                </div>
                </form>
            </div>
        </div>

                </div>
                </form>
            </div>
        </div>
        </div>
    </body>
</html>
